Repository saismrutiranjan18/Tiffin_Fusion, pull requests merged in 2025-01, with the labels that each got.

#5 added workflow
  ,github/ISSUE_TEMPLATE/bug_report.yml
  ,github/ISSUE_TEMPLATE/documentation_update.yml
  ,github/ISSUE_TEMPLATE/feature_request.yml
  ,github/PULL_REQUEST_TEMPLATE.md
Labels: INTERMEDIATE, SWOC

#7 Dockerize application
  Dockerfile
Labels: INTERMEDIATE, SWOC

#9 sign in sign up feature added in navbar with page
  app.js
  index.html
  signin.css
  signin.html
  signin.js
  signup.html
  style.css
Labels: BEGINNER, SWOC

#12 updated newsletter ui
  index.html
Labels: BEGINNER, SWOC

#14 changes in student plan section
  index.html
  studentplan.css
  studentplan.html
  style.css
Labels: INTERMEDIATE, SWOC

#20 contact header updated with bold font and red color
  index.html
  style.css
Labels: BEGINNER, SWOC

#22 Fixes #8
  index.html
  submitQuery.js
Labels: INTERMEDIATE, SWOC

#23 Updated footer with aligned and improved text
  index.html
Labels: BEGINNER, SWOC

#25 contributors page added to website
  contributors/contributor.css
  contributors/contributor.html
  contributors/contributor.js
  index.html
Labels: ADVANCE, SWOC

#29 Solved Privacy Policy Page added
  index.html
  privacy.html
Labels: BEGINNER, SWOC

#30 contributor button positon changed and replaced with image
  Utils/contributor-logo.png
  index.html
  style.css
Labels: BEGINNER, SWOC

#31 changes done for overlapping of meal cards
  studentplan.css
Labels: BEGINNER, SWOC

#33 improvement in ui of 'why tiffin fusion' section with adv effects
  style.css
Labels: BEGINNER, SWOC

#35 responsive design for why tf section
  index.html
  style.css
Labels: BEGINNER, SWOC

#39 Enhanced Footer and Newsletter Alignment (#21)
  index.html
Labels: BEGINNER, SWOC

#42 Api added in contact us form
  index.html
Labels: INTERMEDIATE, SWOC

#41 Enhance Footer and Newsletter Layout (#21)
  Utils/tiffin.png
  Utils/tiffin1.png
  index.html
  style.css
Labels: BEGINNER, SWOC

#44 code of sumbmit query updated
  index.html
  submitQuery.js
Labels: INTERMEDIATE, SWOC

#48 Add Chatbot named "Tiffy" for Enhanced Customer Support and Order Assistance
  index.html
Labels: ADVANCE, SWOC

#50 #46 Issue Fixed Terms&Conditions Page
  Terms.html
  index.html
Labels: INTERMEDIATE, SWOC

#53 footer section responsive
  index.html
Labels: BEGINNER, SWOC

#55 linkedin link added
  index.html
Labels: BEGINNER, SWOC

#56 updated footer to take the same box sizing as of newsletter
  index.html
  style.css
Labels: BEGINNER, SWOC

#58 Link added to footer section of twitter icon
  index.html
Labels: BEGINNER, SWOC

#60 Add Contributors Page
  contributors/1726914447956.png
  contributors/20240921_154411.png
  contributors/contributor.css
  contributors/contributor.html
  contributors/st-3.jpg
  index.html
Labels: INTERMEDIATE, SWOC

#64 Update README.md
  README.md
Labels: documentation, BEGINNER, SWOC

#67 contributor page navbar updated
  contributors/contributor.css
  contributors/contributor.html
Labels: BEGINNER, SWOC

#69 Favicon
  contributors/contributor.html
Labels: BEGINNER, SWOC

#71 link broken issue solved
  contributors/contributor.html
Labels: BEGINNER, SWOC

#72 Added Backend and Signin and Signup
  .env.sample
  .gitignore
  Baselink.js
  Server/.gitignore
  Server/api/app.js
  Server/api/dbconnect.js
  Server/api/index.js
  Server/controller/user.controller.js
  Server/models/user.model.js
  Server/package-lock.json
  Server/package.json
  Server/routes/auth.routes.js
  signin.html
  signin.js
  signup.html
  signup.js
Labels: ADVANCE, SWOC

#77 daily plans page added
  dailyplans.css
  dailyplans.html
  index.html
Labels: INTERMEDIATE, SWOC

#78 [Feature] #18 Created the menu section for the webpage
  Utils/Aloo Gobi.jpg
  Utils/Chapati.jpg
  Utils/Dal Makhani.jpg
  Utils/Dal Tadka.jpg
  Utils/Fruit Salad.jpg
  Utils/Mixed Vegetables.jpg
  Utils/Raita.jpg
  Utils/Salad.jpg
  Utils/Vegetable Curry.jpg
  Utils/steamed rice.jpg
  app.js
  index.html
  style.css
Labels: INTERMEDIATE, SWOC

#80 blog page
  blog.css
  blog.html
  index.html
Labels: INTERMEDIATE, SWOC

#87 Added Backend setup instruction
  README.md
  Server/Readme_Backend.md
  Server/api/app.js
  Server/vercel.json
Labels: INTERMEDIATE, SWOC

#94 Integrated the security page and resolved PR issue #92.
  contactUs.html
  security.css
  security.html
  security.js
Labels: INTERMEDIATE, SWOC

#97 Enhanced the sign in and sign up page
  Utils/facebook.png
  Utils/google.png
  signin.html
  signup.html
Labels: INTERMEDIATE, SWOC

#98 top top scroll button css and js changed
  app.js
  style.css
Labels: INTERMEDIATE, SWOC

#100 heading font changed
  index.html
  style.css
Labels: BEGINNER, SWOC

#101 Changed the Navbar logo image
  Server/package-lock.json
  Server/package.json
  index.html
  style.css
Labels: BEGINNER, SWOC

#105 menu page added with add button
  index.html
  menu-page/menu.css
  menu-page/menu.html
Labels: INTERMEDIATE, SWOC

#104 Added empty blog pages with seperate blog folder
  all_blogs/blog1.html
  all_blogs/blog2.html
  all_blogs/blog3.html
  blog.html
Labels: BEGINNER, SWOC

#107 link broken issue solved
  index.html
Labels: BEGINNER, SWOC

#109 favicon added to menu page
  menu-page/menu.html
Labels: BEGINNER, SWOC

#113 Faster loading fixed
  Utils/facebook.png
  Utils/food-compressed.jpg
  signin.html
  style.css
Labels: INTERMEDIATE, SWOC

#119 Fixed logos in signup page
  signup.html
Labels: BEGINNER, SWOC

#120 Fixed menu page images
  menu-page/menu.html
  menu-page/menu_images/AlooGobi.jpg
  menu-page/menu_images/Chapati.jpg
  menu-page/menu_images/DalMakhani.jpg
  menu-page/menu_images/DalTadka.jpg
  menu-page/menu_images/FruitSalad.jpg
  menu-page/menu_images/Mixed Vegetables.jpg
  menu-page/menu_images/Raita.jpg
  menu-page/menu_images/Salad.jpg
  menu-page/menu_images/VegetableCurry.jpg
  menu-page/menu_images/steamedrice.jpg
Labels: BEGINNER, SWOC

#126 Added cross button for redirection to home
  Utils/cross-icon.png
  signin.css
  signin.html
Labels: BEGINNER, SWOC

#127 Changed color to match UI in student plan page
  package-lock.json
  studentplan.css
  style.css
Labels: enhancement, BEGINNER, SWOC

#123 Add Daily Meal Plan
  dailyplans.css
  dailyplans.html
  dailyplans/Break3.jpg
  dailyplans/Dinner2.jpg
  dailyplans/Dinner3.jpg
  dailyplans/break1.jpg
  dailyplans/break2.jpg
  dailyplans/break4.jpg
  dailyplans/break5.jpg
  dailyplans/break6.jpg
  dailyplans/breakfast.html
  dailyplans/dinner.html
  dailyplans/dinner1.jpg
  dailyplans/dinner4.jpeg
  dailyplans/dinner5.jpg
  dailyplans/dinner6.jpg
  dailyplans/lunch.html
  dailyplans/lunch1.jpg
  dailyplans/lunch2.jpg
  dailyplans/lunch3.jpg
  dailyplans/lunch4.jpg
  dailyplans/lunch5.jpg
  dailyplans/lunch6.jpg
Labels: INTERMEDIATE, SWOC

#129 links added
  dailyplans/breakfast.html
  dailyplans/dinner.html
  dailyplans/lunch.html
Labels: BEGINNER, SWOC

#131 Favicon
  dailyplans/breakfast.html
  dailyplans/dinner.html
  dailyplans/lunch.html
Labels: BEGINNER, SWOC

#137 nav bar issue fixed , now button is working
  menu-page/menu.html
Labels: BEGINNER, SWOC

#138 #89 Made Loader for website
  app.js
  index.html
  style.css
Labels: INTERMEDIATE, SWOC

#140 Added profile Backend
  Server/api/app.js
  Server/controller/profile.controller.js
  Server/routes/profile.routes.js
Labels: ADVANCE, SWOC

#145 Edited dropdown in contact us
  index.html
  style.css
Labels: BEGINNER, SWOC

#146 Fixing login and signup page
  index.html
  signin.html
  signup.html
Labels: ADVANCE, SWOC

#147 Add theme colors to daily plan
  dailyplans/breakfast.html
  dailyplans/dinner.html
  dailyplans/lunch.html
Labels: BEGINNER, SWOC

#148 work us page added to website
  index.html
  submitQuery.js
  work_with_us/work-with-us.css
  work_with_us/work-with-us.html
  work_with_us/work-with-us.js
Labels: ADVANCE, SWOC

#155 Form with the Orange theme + Submit Button animations
  index.html
  style.css
Labels: BEGINNER, SWOC

#156 🔗fix:Create auto-comment.yml
  ,github/workflows/auto-comment.yml
Labels: INTERMEDIATE, SWOC

#157 Added signin sign out button
  index.html
Labels: INTERMEDIATE, SWOC

#161 #160 resolved
  contactUs.html
Labels: BEGINNER, SWOC

#169 Added admin panel backend
  .gitignore
  Server/controller/user.controller.js
  Server/createAdmin.js
  Server/middleware/chekAdmin.midddleware.js
  Server/models/user.model.js
  Server/routes/auth.routes.js
  adminSignin.html
  node_modules/.package-lock.json
  package-lock.json
  package.json
  signin.html
Labels: ADVANCE, SWOC

#167 Make Google button functional
  signin.html
  work_with_us.css
  work_with_us.html
Labels: ADVANCE, SWOC

#173 Broken Link fixed
  index.html
Labels: BEGINNER, SWOC

#178 link added to term of services in footer
  index.html
  work_with_us/work-with-us.html
Labels: BEGINNER, SWOC

#179 domain updated
  signin.html
Labels: BEGINNER, SWOC

#181 font size changed of sign in button of home page on navbar
  index.html
  style.css
Labels: BEGINNER, SWOC

#182 added admin pages
  adminSignin.html
  adminindex.html
  signin.html
Labels: ADVANCE, SWOC

#185 footer added to work with us page
  work_with_us/work-with-us.css
  work_with_us/work-with-us.html
Labels: BEGINNER, SWOC

#188 now logos are working on navbar
  contributors/contributor.html
  index.html
  menu-page/menu.html
  work_with_us/work-with-us.html
Labels: BEGINNER, SWOC

#190 Add Items to Corparate Plan
  corporateplans.css
  corporateplans.html
  corporateplans/nonveg1.jpg
  corporateplans/nonveg2.jpg
  corporateplans/nonveg3.jpg
  corporateplans/nonveg4.png
  corporateplans/nonveg5.jpg
  corporateplans/nonveg6.jpg
  corporateplans/veg1.jpg
  corporateplans/veg2.jpg
  corporateplans/veg3.jpg
  corporateplans/veg4.jpg
  corporateplans/veg5.jpg
  corporateplans/veg6.jpg
  corporateplans/vegan1.jpg
  corporateplans/vegan2.jpg
  corporateplans/vegan3.jpeg
  corporateplans/vegan4.jpg
  corporateplans/vegan5.jpg
  corporateplans/vegan6.jpg
Labels: BEGINNER, SWOC

#202 navbar added to pages
  blog.html
  corporateplans.html
  dailyplans.html
  studentplan.html
Labels: BEGINNER, SWOC

#203 styled sign in button
  index.html
  style.css
Labels: BEGINNER, SWOC

#197 Added new Illustration image and changed Blog titles
  Utils/3.png
  blog.html
  index.html
  lodgecomplaint.html
Labels: enhancement, BEGINNER, SWOC

#210 Individual blog page is added
  all_blogs/blog1.html
  all_blogs/blog2.html
  all_blogs/blog3.html
  blog.css
  blog.html
Labels: BEGINNER, SWOC

#212 Sign In page Password Toggle Bug Fix
  package-lock.json
  signin.html
  signin.js
  signup.html
  signup.js
Labels: BEGINNER, SWOC

#218 Changes in the UI section
  index.html
  style.css
Labels: INTERMEDIATE, SWOC

#206 Footer added to daily meal plan page
  dailyplans.html
Labels: BEGINNER, SWOC

#223 fixed issues in studentplan page
  corporateplans.css
  corporateplans.html
  studentplan.css
  studentplan.html
Labels: BEGINNER, SWOC

#229 Added certificates for contributors.
  contributors/contributor.css
  contributors/contributor.js
Labels: INTERMEDIATE, SWOC

#230 CSS changed
  contributors/contributor.css
Labels: BEGINNER, SWOC

#233 Responsiveness is rectified
  contributors/contributor.css
  contributors/contributor.js
Labels: BEGINNER, SWOC

#234 #220 [Bug] Fixed accessing Homepage from daily meal plans
  dailyplans.html
Labels: BEGINNER, SWOC

#241 Updated
  index.html
  index.js
  style.css
Labels: BEGINNER, SWOC

#242 Report fraud
  index.html
  report-fraud/report-fraud.css
  report-fraud/report-fraud.html
Labels: INTERMEDIATE, SWOC

#237 Add Who we are Page to the Website
  index.html
  whoweare.html
Labels: INTERMEDIATE, SWOC

#243 Fix a small bug on index.html page.
  index.html
Labels: BEGINNER, SWOC

#251 Added contents to Lodge Complaint page
  lodgecomplaint.html
Labels: INTERMEDIATE, SWOC

#254 Added cart functionality
  menu-page/cart.js
  menu-page/checkout.css
  menu-page/checkout.html
  menu-page/checkout.js
  menu-page/menu.html
Labels: INTERMEDIATE, SWOC

#256 Added search functionality in menu
  menu-page/menu.css
  menu-page/menu.html
Labels: BEGINNER, SWOC

#258 added back button in blog.html
  blog.html
  style.css
Labels: BEGINNER, SWOC

#264 FIxed all the links in the footer
  contributors/contributor.html
Labels: BEGINNER, SWOC

#262 Added cart functionality
  corporateplans.html
  dailyplans/breakfast.html
  dailyplans/dinner.html
  dailyplans/lunch.html
  index.html
  studentplan.html
  style.css
Labels: INTERMEDIATE, SWOC

#269 footer added to menu page
  menu-page/menu.html
Labels: BEGINNER, SWOC

#267 fix bug : Navbar Text Animation is Slow
  index.js
Labels: BEGINNER, SWOC

#271 Card Item number
  corporateplans.html
  index.html
  menu-page/cart.js
  menu-page/menu.html
  studentplan.html
Labels: BEGINNER, SWOC

#273 Admin Sign in styling
  adminSignin.css
  adminSignin.html
Labels: BEGINNER, SWOC

#275 Broken link fixed
  signin.html
Labels: BEGINNER, SWOC

#281 #280 Fixed Newsletter Overlay
  style.css
Labels: BEGINNER, SWOC

#259 designed investor relations page
  investor-relations.css
  investor-relations.html
Labels: BEGINNER, SWOC

#287 initialinzed admin backend and added add meal plan controllers
  Server/api/app.js
  Server/controller/admin.controller.js
  Server/middleware/chekAdmin.midddleware.js
  Server/models/menu.model.js
  Server/routes/admin.routes.js
  Server/utils/cloudinary.utils.js
  package-lock.json
  package.json
Labels: ADVANCE, SWOC

#290 footer added to breakfast lunch and dinner plan
  dailyplans/breakfast.html
  dailyplans/dinner.html
  dailyplans/lunch.html
Labels: BEGINNER, SWOC

#301 Payments Page Implementation with Seamless Redirection
  menu-page/checkout.html
  menu-page/payments.css
  menu-page/payments.html
Labels: INTERMEDIATE, SWOC

#302 Added Navbar for Easy Navigation on Checkout Page
  menu-page/checkout.html
Labels: BEGINNER, SWOC

#284 Add footer on studentplan.html page
  studentplan.html
Labels: BEGINNER, SWOC

#303 Here's a refined title for your changes: markdown Copy Edit # Implementation of Custom Scrollbar with Interactive Hover Effect
  style.css
Labels: BEGINNER, SWOC

#310 Change the styling of Cards (Our blog Page)
  blog.css
  blog.html
Labels: BEGINNER, SWOC

#306 made the button align to the theme
  Utils/back-arrow.png
  menu-page/checkout.css
  menu-page/checkout.html
  style.css
Labels: BEGINNER, SWOC
