Repository saismrutiranjan18/Tiffin_Fusion, pull requests merged in 2025-02, with the labels that each got.

#325 Added Testimonials Page
  index.html
  testimonial.css
  testimonial.html
Labels: INTERMEDIATE, SWOC

#326 added some admin pages
  Baselink.js
  Server/createAdmin.js
  Server/package-lock.json
  Server/package.json
  Server/routes/auth.routes.js
  admin-manage-user.html
  admin-meal-item.html
  admin-meal-plan.html
  adminindex.html
Labels: INTERMEDIATE, SWOC

#329 Fix: UCON Overlapping Issue
  style.css
Labels: BEGINNER, SWOC

#331 hamburger fixed
  menu-page/checkout.html
Labels: BEGINNER, SWOC

#335 Add bill and quantity features in checkout.js
  menu-page/checkout.css
  menu-page/checkout.html
  menu-page/checkout.js
Labels: BEGINNER, SWOC

#338 Fixed Menu Search Overlap and Daily Plans
  dailyplans/breakfast.html
  dailyplans/dinner.html
  dailyplans/lunch.html
  menu-page/menu.css
  menu-page/menu.html
Labels: BEGINNER, SWOC

#316 blog page ui fixed
  all_blogs/blog1.html
  all_blogs/blog2.html
  all_blogs/blog3.html
Labels: BEGINNER, SWOC

#344 added manage meal items frontend
  Server/controller/admin.controller.js
  Server/routes/admin.routes.js
  admin-meal-item.html
  adminSignin.html
Labels: INTERMEDIATE, SWOC

#349 total prs count added to contributors card and on contributors certificate
  contributors/contributor.js
Labels: INTERMEDIATE, SWOC

#347 Fix/md format
  README.md
Labels: BEGINNER, SWOC

#350 Add/contributors
  README.md
Labels: BEGINNER, SWOC

#352 added admin controllers like editing and deleteing mealplan and meal items
  .vscode/settings.json
  Server/controller/admin.controller.js
Labels: INTERMEDIATE, SWOC

#356 Added github icon in contributor card
  contributors/contributor.css
  contributors/contributor.js
Labels: BEGINNER, SWOC

#358 Added payment options in footer #336
  all_blogs/blog1.html
  all_blogs/blog2.html
  all_blogs/blog3.html
  blog.css
  blog.html
  contributors/contributor.css
  contributors/contributor.html
  corporateplans.css
  corporateplans.html
  dailyplans.css
  dailyplans.html
  dailyplans/breakfast.html
  dailyplans/dinner.html
  dailyplans/lunch.html
  index.html
  investor-relations.html
  menu-page/menu.css
  menu-page/menu.html
  report-fraud/report-fraud.css
  report-fraud/report-fraud.html
  studentplan.html
  style.css
  testimonial.css
  testimonial.html
  whoweare.html
Labels: BEGINNER, SWOC

#359 customize 404 error page added
  404.html
Labels: INTERMEDIATE, SWOC

#365 added separate controller for resturant and tiffin centres
  Server/controller/resturant.controller.js
  Server/models/restrurant.model.js
Labels: INTERMEDIATE, SWOC

#370 Implemented dark mode
  dark-mode.js
  index.html
  style.css
Labels: JWOC, Hard

#373 added add blog frontend
  addBlog.html
Labels: INTERMEDIATE, SWOC

#377 Dark mode Bug fix issue:-#376
  index.html
  style.css
Labels: BEGINNER, SWOC, JWOC, Easy

#372 Applied transition to the social links
  style.css
Labels: BEGINNER, SWOC, JWOC, Easy

#380 Navbar and footer issue fixed in Lodge Complaint
  lodgecomplaint.html
Labels: BEGINNER, SWOC

#381 Added new css lines to make the meal plan dropdown elements visible in dark mode.
  style.css
Labels: JWOC, Easy

#391 Updated twitter icon to X
  addBlog.html
  all_blogs/blog1.html
  all_blogs/blog2.html
  all_blogs/blog3.html
  blog.html
  contributors/contributor.html
  corporateplans.html
  dailyplans.html
  dailyplans/breakfast.html
  dailyplans/dinner.html
  dailyplans/lunch.html
  index.html
  investor-relations.html
  lodgecomplaint.html
  menu-page/menu.html
  report-fraud/report-fraud.html
  studentplan.html
  testimonial.html
  whoweare.html
  work_with_us/work-with-us.html
Labels: BEGINNER, SWOC, JWOC, Easy

#392 footer added for dark mode for home page
  style.css
Labels: INTERMEDIATE, SWOC

#398 dark mode in all pages
  contactUs.html
  contributors/contributor.css
  contributors/contributor.html
  contributors/contributor.js
  corporateplans.html
  dailyplans.html
  index.html
  investor-relations.html
  lodgecomplaint.html
  security.html
  studentplan.html
  whoweare.html
Labels: INTERMEDIATE, SWOC
