Repository saismrutiranjan18/Tiffin_Fusion, pull requests merged in 2025-04, with the labels that each got.

#448 fixed customize menu button alignment
  index.html
  style.css
Labels: Easy, apertre2.0

#458 footer added to term of services page
  Terms.html
Labels: Easy, apertre2.0

#462 Made the checkout page more responsive
  menu-page/checkout.css
Labels: JWOC, Easy, apertre2.0

#466 Certificate added for apertre 2.0
  contributors/contributor.js
  menu-page/menu.html
Labels: Medium, apertre2.0

#471 Seo meta tags added
  index.html
Labels: Hard, apertre2.0

#477 loader added to customize menu plan page
  corporateplans.html
  customize-menu.html
  dailyplans.html
  studentplan.html
Labels: Medium, apertre2.0

#487 Manage orders admin panel created
  admin-manage-orders.html
  admin-manage-user.html
  admin-meal-item.html
  admin-meal-plan.html
  adminindex.html
Labels: Hard, apertre2.0

#513 payment form redesigned
  Utils/credit-card.png
  menu-page/payments.css
  menu-page/payments.html
Labels: Medium, apertre2.0

#499 Changes the view full menu button
  .vscode/settings.json
  style.css
Labels: Easy, apertre2.0

#519 Footer added to cart page
  customize-menu.html
  menu-page/checkout.html
Labels: Easy, apertre2.0

#498 Add effects to the button
  studentplan.css
  style.css
Labels: Medium, apertre2.0

#536 menu section fixed and now responsive
  style.css
Labels: Medium, apertre2.0

#538 dummy credentials created to access admin dashboard
  adminSignin.html
Labels: Medium, apertre2.0

#544 fix minor changes
  index.html
  style.css
Labels: Easy, apertre2.0

#527 Changes the view more button in dark mode
  style.css
Labels: Easy, apertre2.0

#556 lodge complaint page redesined with updated footer and navbar and dark mode
  lodgecomplaint.html
Labels: Hard, apertre2.0

#561 Hamburger issue fixed of blog page
  blog.html
  customize-menu.html
Labels: Medium, apertre2.0

#563 blog page ui updated and dark mode also added with updated navbar
  blog.css
  blog.html
Labels: Medium, apertre2.0

#565 custom loader added to every blog page
  all_blogs/blog1.html
  all_blogs/blog2.html
  all_blogs/blog3.html
Labels: Medium, apertre2.0

#567 certificates updated according to march 7 to april 13
  contributors/contributor.js
Labels: Easy, apertre2.0

#559 Logo & Favicon
  404.html
  Terms.html
  addBlog.html
  adminSignin.html
  all_blogs/blog1.html
  all_blogs/blog2.html
  all_blogs/blog3.html
  blog.html
  contactUs.html
  contributors/contributor.html
  corporateplans.html
  customize-menu.html
  dailyplans.html
  dailyplans/breakfast.html
  dailyplans/dinner.html
  dailyplans/lunch.html
  favicon.svg
  index.html
  investor-relations.html
  lodgecomplaint.html
  logo.svg
  menu-page/checkout.html
  menu-page/menu.html
  privacy.html
  report-fraud/report-fraud.html
  security.html
  signin.html
  signup.html
  studentplan.html
  testimonial.html
  whoweare.html
  work_with_us.html
  work_with_us/work-with-us.html
Labels: Medium, apertre2.0
