Repository saismrutiranjan18/Tiffin_Fusion, pull requests merged in 2025-03, with the labels that each got.

#400 Adding meal type and image thumbnail
  dailyplans/breakfast.html
  dailyplans/dinner.html
  dailyplans/lunch.html
  index.html
  menu-page/cart.js
  menu-page/checkout.html
  menu-page/checkout.js
  menu-page/menu.html
  studentplan.html
  style.css
Labels: JWOC, Medium

#402 Fixed the back button
  menu-page/checkout.html
Labels: JWOC, Easy

#403 Added the payment gateway
  Server/routes/payment.routes.js
  Server/server.js
  menu-page/payments.html
Labels: JWOC, Hard

#407 darkmode added to footer of home page
  style.css
Labels: Medium, apertre2.0

#412 Create Security.md
  Security.md
Labels: documentation, apertre2.0

#414 Added to cart pop up message, and improvement of Navbar & Footer functionality
  ReusableModal.js
  all_blogs/blog1.html
  all_blogs/blog2.html
  all_blogs/blog3.html
  blog.html
  contactUs.html
  contributors/contributor.html
  corporateplans.html
  dailyplans.html
  dailyplans/breakfast.html
  dailyplans/dinner.html
  dailyplans/lunch.html
  index.html
  investor-relations.html
  lodgecomplaint.html
  menu-page/menu.html
  report-fraud/report-fraud.html
  security.html
  studentplan.html
  testimonial.html
  whoweare.html
Labels: JWOC, Medium, apertre2.0

#418 404 page updated
  404.html
Labels: Hard, apertre2.0

#421 Improve the view more and see our blog buttons
  style.css
Labels: Easy, apertre2.0

#422 fixed issues of 404 page
  404.html
Labels: bug, Easy, apertre2.0

#439 favicon added to security page
  security.html
Labels: Easy, apertre2.0

#445 Contributor page limit increased to 200
  contributors/contributor.js
  lodgecomplaint.html
  privacy.html
  security.html
  style.css
Labels: Medium, apertre2.0
